IntroEF/IntroEF/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IntroEF.Models
{
    public class Student
    {
        
        public int id { get; set; }
        public string name { get; set; }
        public DateTime dob { get; set; }
        public string email { get; set; }
    }
}

IntroEF/IntroEF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntroEF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

IntroEF/IntroEF/Controllers/MyController.cs
using IntroEF.EF;
using IntroEF.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IntroEF.Controllers
{
    public class MyController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Student s)
        {

            UMSEntities db = new UMSEntities();
            var userDetail = new UserDetail
            {
                id = s.id,
                name = s.name,
                dob = s.dob,
                email = s.email
            };
            db.UserDetails.Add(userDetail);
            if (db.SaveChanges() > 0)
            {
                TempData["Msg"] = "User Added";
                return RedirectToAction("Index");
            }
            TempData["Msg"] = "User Not Added";
            return View();
        }
    }
}

IntroEF/IntroEF/Views/My/Create.cshtml
@{
    ViewBag.Title = "Create";
}
<p class="text-danger">
    @Html.ValidationSummary()
</p>
<h2>Index</h2>

<form method="post">
    <input type="number" name="id" placeholder="ID" class="form-control" />
    <p class="text-danger">@Html.ValidationMessage("id")</p>
    <input type="text" name="name" placeholder="Name" class="form-control" />
    <p class="text-danger">@Html.ValidationMessage("name")</p>
    <input type="date" name="dob" placeholder="DOB" class="form-control" />
    <p class="text-danger">@Html.ValidationMessage("dob")</p>
    <input type="text" name="email" placeholder="Email" class="form-control" />
    <p class="text-danger">@Html.ValidationMessage("email")</p>
    <br />

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

IntroEF/IntroEF/Views/My/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

IntroEF/IntroEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "My", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "My", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Create", "Create", "My", new { area = "" }, new { @class = "nav-link" })</li>
                    @*<li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>